### PR TITLE
Remove gh-pages from CI

### PR DESCRIPTION
**Pull request by DirtyF**
not necessary anymore since #20

### CODE REVIEW

**Review by pathawks — APPROVED** [review]

**Review by parkr — APPROVED** [review]

**Comment by DirtyF** [comment]
@jekyllbot: merge +site

**Comment by ghost** [comment]
@jekyllbot have mercy

**Comment by pathawks** [comment]
I don't think @jekyllbot has been added to this repo

**Comment by DirtyF** [comment]
@pathawks right, PR submitted https://github.com/parkr/auto-reply/pull/18

**Pull request merged**
