### PR TITLE
Update footer to match jekyllrb.com

### PR DESCRIPTION
**Pull request by pathawks**

### CODE REVIEW

**Comment by pathawks** [comment]
Looks like we'll need to add a `LICENSE`

**Review by parkr — DISMISSED** [review]
I'd use some Creative Commons license. It uses the branding from Jekyll so whatever that license is -- see jekyll/brand for details.

**Comment by pathawks** [comment]
[CC-BY 4.0](https://github.com/jekyll/brand/blob/c16513ce43d8906881484046e9ef0babed12ff5f/LICENSE)

---

Added in #23

**Review by DirtyF — DISMISSED** [review]

**Comment by pathawks** [comment]
footer

I've updated the license name (as appropriate).

Could @parkr and @DirtyF just look over one more time to make sure it all looks ok?

**Review by parkr — COMMENTED** [review]
Looks good to me! :+1:

**Review by DirtyF — APPROVED** [review]

**Pull request merged**
