### PR TITLE
Mention Github Pages support and compatibility

### PR DESCRIPTION
**Pull request by DirtyF**
Introduce two optional YFM variables: 

```yaml
 - compatible : v3
 - github_pages: true
````

Basic information display for now.

### CODE REVIEW

**Comment by pathawks** [comment]
Would it be more maintainable to keep a `_data` file with plugins available on GHP, and check a plugins name against that list?

**Comment by DirtyF** [comment]
@pathawks good idea, I was thinking of using https://pages.github.com/versions.json but it contains more than plugins.

**Comment by pathawks** [comment]
And there's no good way for us to just pull that in at build time, is there? I guess it's going to be manual updating either way.

Maybe during CI, we could make sure that anything claiming to be in GHP is listed in the current `versions.json`?

**Comment by DirtyF** [comment]
@pathawks here comes the :octocat:

**Review by pathawks — APPROVED** [review]
LGTM :heart:

**Review by parkr — APPROVED** [review]
💗

**Comment by DirtyF** [comment]
@jekyllbot: merge

**Pull request merged**
